### ISSUE TITLE
Can't get this to work on Windows

### ISSUE THREAD

**Issue by y3nd** [123456abcdef/cr-sc-dump#1]
Hi!
The lzma package can't be compiled on Windows (with Python 2.7), so I used Python 3 (with native support of lzma : https://docs.python.org/3/library/lzma.html).
But it doesn't work too :

```
C:\Users\y3n\Documents\Projects\cr-sc-dump>python dumpsc.py chr_skeleton_tex.sc
chr_skeleton_tex.sc
Traceback (most recent call last):
  File "dumpsc.py", line 99, in <module>
    process_sc(baseName, data[26:], path)
  File "dumpsc.py", line 44, in process_sc
    data = data[0:9] + ('\x00' * 4) + data[9:]
TypeError: can't concat bytes to str
```

Please help me,

Thx

**Comment by 123456abcdef** [comment]
Yeah this version only works with Python 2.7. You could try to install a different lzma implementation for Python 2.7.
Or you could try if [this](https://gist.github.com/123456abcdef/9554585f8a3d695e6d915c4f2b69c991) version works for you with Python 3.

**Comment by y3nd** [comment]
It's working ! Thanks a lot for the Python 3 version !

**Comment by 123456abcdef** [comment]
Cool! Thanks for the feedback!
