### ISSUE TITLE
how to use cr-sc-dump

### ISSUE THREAD

**Issue by qgz1989** [123456abcdef/cr-sc-dump#12]
I always get an error when I enter the following command in the console：
python dumpsc.py C:\Users\KID\Desktop\CC\SC-Assets-Downloader-GUI-master\output\96f15130347e2669f85dca5769def13e2e541912\sc/to/arena_training_tex.sc

Error:FileNotFoundError [Errno 2] No such file or directory: 'C:\\Users\\KID\\Desktop\\CC\\SC-Assets-Downloader-GUI-master\\output\\96f15130347e2669f85dca5769def13e2e541912\\sc/to/arena_training_tex.sc'

Storage path of all downloaded SC files：C:\Users\KID\Desktop\CC\SC-Assets-Downloader-GUI-master\output\96f15130347e2669f85dca5769def13e2e541912\sc

The name of the file I want to convert：arena_training_tex.sc

**Comment by qgz1989** [comment]
please help

**Comment by 123456abcdef** [comment]
The error you get says that the file does not exists. Comparing to your storage path there is an additional **to** in your path `C:\Users\KID\Desktop\CC\SC-Assets-Downloader-GUI-master\output\96f15130347e2669f85dca5769def13e2e541912\sc/**to**/arena_training_tex.sc`.
Maybe that is your problem?

I think `SC-Assets-Downloader-GUI` can decompress the SC files automatically, so you might not need to run `dumpsc.py`. Just check the checkbox `Enable LZMA/LZHAM decompression for CSV / SC files`.

**Comment by qgz1989** [comment]
SC-Assets-Downloader-GUI is a great tool, I have got all the csv files
But how to pictures from the "_tex.sc" file?
I open all the "_tex.sc" files are a bunch of garbled characters

**Comment by 123456abcdef** [comment]
Just call `python dumpsc.py C:\Users\KID\Desktop\CC\SC-Assets-Downloader-GUI-master\output\96f15130347e2669f85dca5769def13e2e541912\sc\arena_training_tex.sc` and you should get a PNG.
