### ISSUE TITLE
Unknown header (dl.sc)

### ISSUE THREAD

**Issue by Hit1ove** [123456abcdef/cr-sc-dump#13]
Why does not it work? What should be done?

_C:\DECODE\cr-sc-dump-master>python dumpsc.py ex/emotes_bday_03_dl.sc --old
ex/emotes_bday_03_dl.sc
Exception   Unknown header_

**Comment by 123456abcdef** [comment]
`Exception Unknown header` indicates the file you passed is not a `sc` file. The first two bytes should be `0x53 0x43`.
For me its working fine. Tested with
`python dumpsc.py --old emotes_bday_03_dl.sc`
`emotes_bday_03_dl.sc` (md5: `3e62a5993b8cf6de3d8cfc29a4e5b625`, cr-fingerprint: `e49eab889ba99cdf0e40d98b8b3e38b5ff443d38`)

What version of `emotes_bday_03_dl.sc` are you using?

**Comment by Hit1ove** [comment]
> What version of `emotes_bday_03_dl.sc` are you using?

this is [https://www.mediafire.com/file/9ion8krlbbvdc2m/emotes_bday_03_dl.sc/file](https://www.mediafire.com/file/9ion8krlbbvdc2m/emotes_bday_03_dl.sc/file)

**Comment by 123456abcdef** [comment]
The file you provided is already decompressed. You have to provide the original (compressed) file to this script.

**Comment by Hit1ove** [comment]
> The file you provided is already decompressed. You have to provide the original (compressed) file to this script.

How to get PNG from top SC file?

**Comment by 123456abcdef** [comment]
If you really want to process your provided file, apply the following changes.
Line 113-117:
```python
# decompressed = decompress(data[26:])

# md5_hash = data[10:26]
# if hashlib.md5(decompressed).digest() != md5_hash:
#     raise Exception("File seems corrupted")
decompressed = data
```
Line 195:
```python
# file_type  = check_header(data)
file_type = "sc"
```
Then execute the script again `python dumpsc.py --old emotes_bday_03_dl.sc`.

(I still recommend using the original file.)

**Comment by Hit1ove** [comment]
> If you really want to process your provided file, apply the following changes.

Thank you, it works
