### ISSUE TITLE
lzma

### ISSUE THREAD

**Issue by sit-on-the-moon** [123456abcdef/cr-sc-dump#14]
it cannot work seemingly
![707da986d6297d6b](https://user-images.githubusercontent.com/98571615/152141853-a3c6d082-813e-4fcc-98c6-1ceffdd2bf71.jpg)
.

**Comment by 123456abcdef** [comment]
Please provide the following infos so I am able to help you. 
1. Where did you get your _sc.tex file from? E.g. APK version or similar.
2. Your complete command line call. Please copy&paste the call or provide a screenshot. Please do not take a photo of your monitor ;).

**Comment by sit-on-the-moon** [comment]
1.I got them from version 3.5.0.
2.I copied dumpsc.py into ./assets/sc folder and ran "find . -name '*_tex.sc' | xargs python ./dumpsc.py" there.
![屏幕截图 2022-02-09 152703](https://user-images.githubusercontent.com/98571615/153142165-920673ac-0fd0-4d18-9328-1ee564499465.png)

**Comment by 123456abcdef** [comment]
Works fine on my end. Clash Royale 3.5 APK.
``` console
$ sha1sum arena_training_tex.sc 
6145f920e0b7498b68747729c849e783581271d0  arena_training_tex.sc
$ python dumpsc.py arena_training_tex.sc 
arena_training_tex.sc
  file_type: 28, file_size: 3949845, sub_type: 0, width: 970, height: 1018
  file_type: 28, file_size: 2002605, sub_type: 4, width: 850, height: 1178
```

Did you apply any other scripts to your files?

**Comment by sit-on-the-moon** [comment]
I remember I didnot.This is the result on my end.

$ sha1sum arena_training_tex.sc
8f4513094d2767dc2daad5832aeda33303074346  arena_training_tex.sc
$ python dumpsc.py arena_training_tex.sc
arena_training_tex.sc
Traceback (most recent call last):
  File "dumpsc.py", line 119, in <module>
    process_sc(baseName, data[26:], path)
  File "dumpsc.py", line 41, in process_sc
    decompressed = lzma.LZMADecompressor().decompress(data)
_lzma.LZMAError: Input format not supported by decoder

**Comment by 123456abcdef** [comment]
It seems like that your files were already edited, that's why the script complaints that the content is not compressed. From your screenshot I see that you also have *_dl.sc files. These files usually don't come with the APK but are downloaded. Did you get your files from a real devices or did you use a download script?

**Comment by sit-on-the-moon** [comment]
Let me see.To get former version of Clash Royale,i downloaded an apk navigated to a private server.Maybe that is the reason.
What should i do next?Is it necessary to delete statements with "lzma"?

**Comment by sit-on-the-moon** [comment]
Let me see.To get former version of Clash Royale,i downloaded an apk navigated to a private server.Maybe that is the reason.
What should i do next?Is it necessary to delete statements with "lzma"?

**Comment by 123456abcdef** [comment]
Your files might be modified but I do not know. If you just want an older APK version you can try sites like https://apkpure.com/

**Comment by sit-on-the-moon** [comment]
OK.Thank you very much.
