### ISSUE TITLE
Can't decryption sc file (no module named 'PIL')

### ISSUE THREAD

**Issue by hiendo3d** [123456abcdef/cr-sc-dump#15]
Hi, I try to use dumpsc but not work. Can you help me?
![Untitled (1)](https://user-images.githubusercontent.com/99595169/155518950-f65eb7b0-e628-4d05-938d-3e6da3d0abb2.png)
?

**Comment by 123456abcdef** [comment]
Can you please check that your pip installs Pillow for the correct Python installation?

**Comment by hiendo3d** [comment]
Thanks for your replying. but I cant decode sc files
https://drive.google.com/file/d/1MjmCsnhhj8W171GXUseK6PWK881_wCYK/view?usp=sharing
![Untitled (1)](https://user-images.githubusercontent.com/99595169/155889676-df3f0447-d4ef-4fcf-a99d-81d1343b3943.png)
.

**Comment by 123456abcdef** [comment]
Could you please try without `--old`?

In case it won‘t work please tell from where you got your `_tex.sc` file from.

**Comment by hiendo3d** [comment]
It's from: https://github.com/Galaxy1036/SC-Assets-Downloader-GUI

**Comment by 123456abcdef** [comment]
This tool has the option to decompress the `sc` files after download (see https://github.com/Galaxy1036/SC-Assets-Downloader-GUI/blob/master/ui/download_widget.py#L99).
Make sure to uncheck this box.

**Comment by hiendo3d** [comment]
Yes, thank you for supporting.
