### ISSUE TITLE
clash of quest cant dump

### ISSUE THREAD

**Issue by 1501432163** [123456abcdef/cr-sc-dump#16]
clash of quest's sc cant dump

**Comment by 1501432163** [comment]
[map.zip](https://github.com/123456abcdef/cr-sc-dump/files/8401744/map.zip)

**Comment by 1501432163** [comment]
[map.sc.txt](https://github.com/123456abcdef/cr-sc-dump/files/8401746/map.sc.txt)

**Comment by 1501432163** [comment]
like this;
help!

**Comment by 1501432163** [comment]
thank you for read this

**Comment by 123456abcdef** [comment]
Quick fix: [dumpsc.py](https://gist.github.com/123456abcdef/7c7c863d9775d5bf7840cebac2b248f1)
Additionally install `zstandard` before using: `pip install zstandard`

I might fix this repo later.
