### ISSUE TITLE
HAY DAY SOME TEX / SC cannot get image

### ISSUE THREAD

**Issue by EscobarMoney** [123456abcdef/cr-sc-dump#17]
![image](https://user-images.githubusercontent.com/62748321/193317824-2cb83339-793a-4bf4-9722-c9339936059c.png)
There is my code, everything is up to date

**Comment by anthonypacini** [comment]
i am having this same problem

**Comment by viphakorn** [comment]
is clash royale work? 
I dont know how to use it

**Comment by 123456abcdef** [comment]
Should be fixed at least for COC, CR and HD. Please verify.
Use Python < 3.10 in case of LZHAM

**Comment by viphakorn** [comment]
yes, please fix coc and cr

**Comment by 123456abcdef** [comment]
> yes, please fix coc and cr 

Like I said, it should be working fine for CoC and CR.
Did you encounter any problems?
