### ISSUE TITLE
Decoder Error LZMA

### ISSUE THREAD

**Issue by viphakorn** [123456abcdef/cr-sc-dump#18]
![Screenshot (2)](https://user-images.githubusercontent.com/94034327/198295687-e6780b0f-677f-482c-983b-6a832e02249c.png)

I try python 3.9 and 3.10 both get same error.
maybe I do something wrong?

**Comment by 123456abcdef** [comment]
Just tested with `ui_tex.sc` from the latest version `3.3024.3` of CR and it works fine for me. How old is your input file? Did you get it from an APK?

**Comment by viphakorn** [comment]
I download APK from [apkpure](https://m.apkpure.com/clash-royale/com.supercell.clashroyale) latest version and
still get error. 

Powershell:
`PS D:\cr\clash_royale_3.3024.3\assets\sc> py dumpsc.py ui_tex.sc`
`ui_tex.sc`
`LZMAError Input format not supported by decoder`

what is python version you use?

**Comment by anno73** [comment]
I am using python3.10 in wsl2.

And just to be sure, I tried it on Clash of Clans APK, not Clash Royale :-)

**Comment by viphakorn** [comment]
thanks it's work!
but I don't know  why it's doesn't work on windows 10 pro .
