### ISSUE TITLE
LZMAError

### ISSUE THREAD

**Issue by openSourceBugs** [123456abcdef/cr-sc-dump#21]
I ran through the setup and executed the command:

python dumpsc.py chr_goblin_archer_tex.sc
chr_goblin_archer_tex.sc
LZMAError Input format not supported by decoder

Not sure what this means.

**Comment by fdgggy** [comment]
same with me

**Comment by 123456abcdef** [comment]
Sorry for the late response.

Just tested myself with `md5:eab13a58d4b7e769693a1b926edabca6  chr_goblin_archer_tex.sc` from APK version `3.3074.6`. Works fine for me.

What OS and Python version are you using?

**Comment by MFpX13cumseeme** [comment]
Strategic code space allow certain associations to communicate thru simple code of movement commander 1 will respond to each of the following commands received. Elite olo

**Comment by openSourceBugs** [comment]
i think it was python 3.10 and windows 10
