### ISSUE TITLE
.csv Unknown header

### ISSUE THREAD

**Issue by mostlystorage** [123456abcdef/cr-sc-dump#22]
Hi!
I'm having trouble using the script:
Any .csv file gives Exception Unknown header
Any .sc file gives LZMAError Input format not supported by decoder

OS: Windows 11 Version	10.0.22621 Build 22621
Python: 3.10.11
Packages: Pillow-9.5.0 pylzham-0.1.3 zstandard-0.21.0
Res source: CoC 15.83.29

Any help will be appreciated, thank you

**Comment by mostlystorage** [comment]
UPD: I've noticed that script is checking for first byte to be 0x5b, which is true for the .csv files stored in /csv. However, for the /logic .csv files, the first bytes follow this pattern: 5369 673a
Is there a way to decode those?

**Comment by 123456abcdef** [comment]
~~csv: Never tried to uncompress the `*.csv` files under `/logic`. I don't know what the file format is.~~
Edit: Nvm, just pushed changes. Try if it works for you.

sc: This script can only extract pngs from `*_tex.sc` files. Those are working fine for me. Did you try to extract pngs from the wrong files?

**Comment by mostlystorage** [comment]
works. ty!
