### ISSUE TITLE
LZMAError Input format not supported by decoder

### ISSUE THREAD

**Issue by ToxifireX** [123456abcdef/cr-sc-dump#23]
\path\to\assets\sc\ui_spells.sc --old
ui_spells.sc
**LZMAError Input format not supported by decoder**

\path\to\assets\sc\ui_spells.sc
ui_spells.sc
**LZMAError Input format not supported by decoder**

I am using python 3.11.5 (latest 09/02/23)
I have retrieved the Clash Royale files by installing them from [apkpure.com](https://apkpure.com/clash-royale/com.supercell.clashroyale/download) Clash Royale version 3.33145, then renaming the file to end in .zip, and extracting.
I am using Windows 10 Pro OS Build 19045.3324 on Command Prompt (cmd).

**Comment by 123456abcdef** [comment]
Try using `ui_spells_tex.sc` if available. If I remember correctly Most of CR's `*.sc` don't contain PNGs.

**Comment by ToxifireX** [comment]
Alright. Thank you.

**Comment by 123456abcdef** [comment]
Did it work with using `*_tex.sc` files?

**Comment by ToxifireX** [comment]
Yea, it did. I decompressed all of them, but didn't find the card icons for a lot of cards.
I noticed that some of the newer cards are in their own `ui_spell_[card].sc` file, and not `ui_spells_tex.sc`. For example, `ui_spell_zappies.sc` & `evolution_mortar.sc`. I noticed there are no tex.sc to match these.
I am trying to get the evolution mortar.png.
Thanks

**Comment by 123456abcdef** [comment]
Most of the `*.sc` are not part of the APK itself but get downloaded when you start the app on your device. This way SC can easier update most of their assets.
There are two ways to get the additional files, pull them directly from your device or use [sc-assets-download](https://github.com/123456abcdef/sc-assets-download). For the latter you might need to update some hashes/version numbers in the code itself to pull the newest files.

**Comment by ToxifireX** [comment]
Ok, I didn't know that and thanks I will try it.

**Comment by ToxifireX** [comment]
Hi, do you know where I can find the evolution card icon images? Like this one:
![image](https://github.com/123456abcdef/cr-sc-dump/assets/143912331/f8cdf2b5-b7b0-4790-8d3a-fd7fd1f6ef2d)

Ok, I found it in spells_evolved.csv, but I run into the same issue that I opened this issue for. The file is ui_spells_mortar_evolution.sc, but it runs into the LZMA issue. Do you know any way that I can decode it? Thanks.

**Comment by 123456abcdef** [comment]
`python dumpsc.py --old ui_spell_mortar_evolution.sc`

Exactly how it is explained in the `README.md`.

**Comment by ToxifireX** [comment]
![Capture](https://github.com/123456abcdef/cr-sc-dump/assets/143912331/ad8d5149-d5d5-41fe-b417-3476100f1db5)

**Comment by 123456abcdef** [comment]
Ok figured it out for some reason `zstandard.MAGIC_NUMBER` returns a different value on Windows than on Linux.
Could you please change [line 55](https://github.com/123456abcdef/cr-sc-dump/blob/master/dumpsc.py#L55) from
```python
elif int.from_bytes(data[0:4], byteorder="little") == zstandard.MAGIC_NUMBER:
```
to
```python
elif int.from_bytes(data[0:4], byteorder="little") == 0xfd2fb528:
```
In the meantime I try to figure out why there is a OS specific difference.

**Comment by ToxifireX** [comment]
Alright, thanks for looking into it, and I will try it and let you know the result when I get the chance.

**Comment by ToxifireX** [comment]
Thanks you so much for helping me, and it has worked. One last question: are `*.sc` files and `*_tex.sc` files coded in the same way? Thanks again.

**Comment by 123456abcdef** [comment]
Thank you for hanging on and testing in your environment.
There are `*.sc`, `*_dl.sc`, and `*_tex.sc` depending on the game they are compressed with different algorithms.
`*_dl.sc` and `*_tex.sc` only contain assets. `*.sc` sometime contain assets.
Never really investigated the `*.sc` further.

**Comment by ToxifireX** [comment]
Do you know what type of compression each file uses in Clash Royale? I tried to figure it out using `--verbose` in your code, but it always says `Decompressing using ZSTD`. However, when I use Galaxy1036's code, it says `LZMA Compression Detected` every time. I am interested because I would like to recompress the files in their original compression.

**Comment by 123456abcdef** [comment]
If the script prints `Decompressing using ZSTD ...` it should be correct otherwise it is `LZMA` or `LZHAM`. What compression is used is not depending on the game but on the file header itself. I'm not to sure about the logic when what compression is used.

**Comment by ToxifireX** [comment]
Alright, thank you for helping me along the way. I'll close this issue now.
