### ISSUE TITLE
Decoding does not work for CoC v16.0.4 apk

### ISSUE THREAD

**Issue by Find-fengqingwu** [123456abcdef/cr-sc-dump#25]
Under the 16.0.4 version, most files in the SC cannot be decoded.

**Comment by viphakorn** [comment]
same here not working on clash royale since 2024

**Comment by 123456abcdef** [comment]
SC added new file types 45 and 47. Those files have the file format [KTX](https://registry.khronos.org/KTX/specs/1.0/ktxspec.v1.html). For handling I had to add an additional dependency called [texture2ddecoder](https://pypi.org/project/texture2ddecoder/).

Tested with BS, COC and CR. Please verify for yourself 50241f9650d92a2f27c2180cbc779c6aa5c49501.

**Comment by Stallion77RepoOfficial** [comment]
Please port pylzham to silicon macs. I cant download giving error because of dependencies of windows I think

**Comment by 123456abcdef** [comment]
@Stallion77RepoOfficial Please open a new issue [here](https://github.com/Galaxy1036/pylzham).
Please provide info about your environment and the exact error you get.
I don't think a Windows dependency is the problem.

**Comment by Teroa** [comment]
> Please port pylzham to silicon macs. I cant download giving error because of dependencies of windows I think

You can utilize Docker to run this tool on Apple Silicon successfully. It works perfectly for me.
