### ISSUE TITLE
dump can not decrypt .sc/_tex.sc to png in Squad Busters

### ISSUE THREAD

**Issue by Darklighture** [123456abcdef/cr-sc-dump#28]
it said ValueError not enough image data
btw it can decrypt csv

**Comment by 123456abcdef** [comment]
The `*_tex.sc` files are referencing the `*.sctx` files. These are new. At the first glance I could not figure out how to read them. Will look into it another day.
Help is always appreciated.

**Comment by 123456abcdef** [comment]
I made some progress. The previous introduced file type [KTX](https://registry.khronos.org/KTX/specs/1.0/ktxspec.v1.html) was replaced in favor of their own file type `SCTX`. Image data is now zstd compressed to reduce file sizes.
I wasn't able to figure out the complete file structure yet. What is missing is how to figure out the image format. Before it was encoded as [gl_internal_format](https://github.com/123456abcdef/cr-sc-dump/blob/50241f9650d92a2f27c2180cbc779c6aa5c49501/dumpsc.py#L164) and could be looked up [here](https://github.com/google/fplbase/blob/4c9f5b751427f3be56a9277497b9078079aa1b9c/include/fplbase/glplatform.h#L235).

At the moment the image format is hard coded. Some `*_tex.sc` files referencing a `*.sctx` file are already correctly processed. Check out the latest commit.

Will continue another day.

**Comment by Darklighture** [comment]
it seems has something wrong with _tex.sc to png in CR version 5.01 since Jan. (it can still work in Oct. 2023 version 4.00)
and I found this may help https://github.com/sc-workshop/SC

**Comment by 123456abcdef** [comment]
Check last commit.
