### ISSUE TITLE
buffer error

### ISSUE THREAD

**Issue by Hamid-Najafi** [123456abcdef/cr-sc-dump#4]
i get this error !

struct.error: unpack_from requires a buffer of at least 116960 bytes

can you help?
Tahnks

**Comment by 123456abcdef** [comment]
I couldn't reproduce your error with the latest apk. What OS, python version do you use and on which file occurs this error?

**Comment by 123456abcdef** [comment]
No response, closing.

**Comment by Hamid-Najafi** [comment]
Windows 10, Python2.7,on any ***_tex.sc  i get this !
its latest apk.
tested on different pc (windows 10 and same python,and two needed lib were installed !)
here is a shot

**Comment by 123456abcdef** [comment]
:D.
I try to reproduce with a virtual machine, when I have time.

**Comment by Goldenstarc** [comment]
i found a solution here but didnt work!
[http://stackoverflow.com/questions/33799683/error-unpack-from-requires-a-buffer/33799954](url)
windows cant find <<import lzma>>
and i changed all <<lzma>> to lzmaffi
im jsut looking for decoded files and found them somewhere but thoose are too old !

**Comment by Hamid-Najafi** [comment]
i found a solution here but didnt work!
http://stackoverflow.com/questions/33799683/error-unpack-from-requires-a-buffer/33799954

im jsut looking for decoded files and found them somewhere but thoose are too old !
could you say me your os and python version?
some thing else , could you please upload decoded sc?
Thanks :)

**Comment by 123456abcdef** [comment]
It is working for me even on Windows 10 and I don't know what is causing the problem for you. You could try to run an older commit which was for **Python 3** (https://github.com/123456abcdef/cr-sc-dump/blob/580f3a3a47af3d7333f82ef67acf78b1c6547a1d/dumpsc.py). You need to install Pillow, lzma is already included in Python 3.

I can't share copyrighted material here, so try the other version.

**Comment by Hamid-Najafi** [comment]
nice ! 
no compile error 
it worked but bigger problem, can you tell me what is this for !!!? 
windows cant load it !
http://uploads.im/zIDBX.jpg
"I can't share copyrighted material here, so try the other version."
ok ,get it,i try to decode it
thanks :)

**Comment by 123456abcdef** [comment]
You should be able to open the pngs even with Windows built in preview. Do your pngs have a reasonable file size? For example _building_basic_cannon_tex.png_ should have a size of _107.577 Bytes_. But I can only guess what is going wrong on your side.

**Comment by Hamid-Najafi** [comment]
mine size is 63,921 bytes!
ops,did you tested that version with python3 ?

**Comment by 123456abcdef** [comment]
The commit mentioned above is working for me with Python 3.5 on WIndows 10. But this version is still using **struct.unpack** which I guess throws the error you mentioned in your first post. Maybe there is still a problem. You have to test that yourself, I don't know what could cause your problem.

**Comment by Hamid-Najafi** [comment]
finally worked in ubuntu 
but i have no idea about windows !
