### ISSUE TITLE
Sample files for all older formats?

### ISSUE THREAD

**Issue by jleclanche** [123456abcdef/cr-sc-dump#7]
Do you have reference files or something for the old formats? I'd like to get this merged into upstream Pillow.

**Comment by 123456abcdef** [comment]
If you want the files before Supercell added filetype 27 & 28, then you can find and older Version on [APKPure](https://apkpure.com/clash-royale/com.supercell.clashroyale/download/88-APK?from=details%2Fversion).

Besides that nothing changed regarding "*_tex.sc"

**Comment by jleclanche** [comment]
How many different versions of the file format are we talking about? I'm really only looking for one or two examples per format but I'd like to be exhaustive and have at least one for each in the tests.

**Comment by xhuliobedulla** [comment]
Guys,we all know about _tex.sc but how can we find whats inside the *.sc?
Any of you have found a way to find what they are?

**Comment by 123456abcdef** [comment]
Then just use the latest apk there should be all types used. You could run this script on all files and check the terminal output. Then you can pick a few examples to cover all. Shouldn't be that many. Maybe 5-6 different types.

**Comment by jleclanche** [comment]
Thanks!

**Comment by 123456abcdef** [comment]
@xhuliobedulla look [here](https://github.com/Galaxy1036/sc_decode). But I don't know what you can do with it.

**Comment by xhuliobedulla** [comment]
Thanks,thats only for textures and i already have them. Im just curious to
see what's inside the *.sc files .i have been searching to find what they
keep inside but it is too hard to decode them 😥😥
