### ISSUE TITLE
Issue with new cards

### ISSUE THREAD

**Issue by MaherFa** [123456abcdef/cr-sc-dump#8]
a while back SC started using a new way of storing new cards
and I failed to "unpack" said cards using this tool
the cards are

- ui_spell_zappies.sc
- ui_spell_hunter.sc
- ui_spell_magic_archer.sc
- ui_spell_ghost.sc

and they can be found in `data\data\update`
any help would be apriciated

**Comment by Galaxy1036** [comment]
they use an old way were they store texture directly into the .sc, you can unpack textures using this tool: https://github.com/Galaxy1036/Old-Sc-Dumper

**Comment by MaherFa** [comment]
This actually worked!
What a legend, much appreciated, Thank you.
